// Curated list of major U.S. health-insurance payers and common plan brands.
// Not exhaustive — the provider field accepts free text for anything not listed.
// Florida-relevant plans (Florida Blue, Simply Healthcare, Sunshine Health,
// AvMed, Molina Florida) are included alongside national carriers since this
// site serves the West Palm Beach / South Florida area.
export const INSURANCE_PROVIDERS = [
  "Aetna",
  "Ambetter",
  "AmeriHealth",
  "Anthem Blue Cross Blue Shield",
  "AvMed",
  "Beacon Health Options",
  "Blue Cross Blue Shield",
  "Carelon Behavioral Health",
  "CareSource",
  "Cigna",
  "ComPsych",
  "Elevance Health",
  "First Health",
  "Florida Blue",
  "Florida Health Care Plans",
  "GEHA",
  "Health Net",
  "Highmark",
  "Humana",
  "Kaiser Permanente",
  "Magellan Health",
  "Medicaid",
  "Medicare",
  "Meritain Health",
  "Molina Healthcare",
  "MultiPlan",
  "Optum",
  "Oscar Health",
  "Oxford Health Plans",
  "PHCS",
  "Simply Healthcare",
  "Sunshine Health",
  "TRICARE",
  "UMR",
  "UnitedHealthcare",
  "WellCare",
];
