"use client";

import Image from "next/image";
import { useRef, useState } from "react";
import { Play } from "lucide-react";

/** 16:9 for the landscape brand film, 9:16 for the vertical social reel. */
type Aspect = "video" | "portrait";

const aspects: Record<Aspect, string> = {
  video: "aspect-video",
  portrait: "aspect-[9/16]",
};

export default function BrandVideo({
  src,
  poster,
  label = "Play the Seaside Wellness story",
  aspect = "video",
  sizes = "100vw",
  captionsSrc,
  transcript,
  transcriptLabel = "Read the transcript",
  captionsLabel = "English",
}: {
  src: string;
  poster: string;
  label?: string;
  aspect?: Aspect;
  /** Poster-image sizes hint — narrow this when the player sits in a column. */
  sizes?: string;
  /** WebVTT caption track. Generated by scripts/build-vtt.mjs. */
  captionsSrc?: string;
  /**
   * Track label shown in the player's caption menu.
   *
   * Say what the track actually contains. The brand film's cues were transcribed
   * from its on-screen cards and cover ~22% of a runtime that carries continuous
   * audio, so labelling it a plain "English" caption track would assert a
   * completeness nobody has verified — and a viewer who enables it would have no
   * cue that the rest is untranscribed. Revert to "English" once someone who can
   * hear the audio confirms the cues are complete (SW-007).
   */
  captionsLabel?: string;
  /**
   * Text alternative, rendered in a disclosure below the player.
   *
   * Not optional in spirit: this film carries its narrative in full-screen text
   * cards, and burned-in text is an image — so without this the story is
   * unavailable to screen-reader users no matter what the audio does.
   */
  transcript?: string[];
  transcriptLabel?: string;
}) {
  const ref = useRef<HTMLVideoElement>(null);
  const [playing, setPlaying] = useState(false);

  const start = () => {
    setPlaying(true);
    requestAnimationFrame(() => ref.current?.play());
  };

  return (
    <div>
      <div
        className={`relative ${aspects[aspect]} overflow-hidden rounded-2xl bg-ink shadow-[var(--shadow-lift)] ring-1 ring-shell`}
      >
        <video
          ref={ref}
          src={src}
          poster={poster}
          controls={playing}
          preload="none"
          playsInline
          className="h-full w-full object-cover"
          // No crossOrigin: the caption track is served same-origin, which needs
          // none. If the video ever moves to a CDN (VID-4), add
          // crossOrigin="anonymous" and make sure the CDN sends CORS headers —
          // otherwise the track silently fails to load.
        >
          {captionsSrc && (
            <track
              kind="captions"
              src={captionsSrc}
              srcLang="en"
              label={captionsLabel}
              default
            />
          )}
        </video>
        {!playing && (
          <button
            type="button"
            onClick={start}
            aria-label={label}
            className="group absolute inset-0 grid place-items-center"
          >
            <Image src={poster} alt="" fill sizes={sizes} className="object-cover" />
            <span className="absolute inset-0 bg-gradient-to-t from-ink/60 via-ink/20 to-ink/30" />
            <span className="relative grid size-20 place-items-center rounded-full bg-white/95 text-gold-600 shadow-xl transition-transform duration-300 group-hover:scale-110">
              <Play className="size-8 translate-x-0.5 fill-current" />
            </span>
            <span className="absolute bottom-6 left-6 right-6 text-left font-display text-2xl text-white sm:text-3xl">
              {label}
            </span>
          </button>
        )}
      </div>

      {transcript && transcript.length > 0 && (
        <details className="group mt-4 rounded-xl border border-shell bg-cream px-5 py-4">
          <summary className="cursor-pointer list-none text-sm font-semibold text-ink-700 transition-colors hover:text-gold-800">
            {transcriptLabel}
            <span className="ml-1.5 inline-block text-ink-500 transition-transform group-open:rotate-90">
              &rsaquo;
            </span>
          </summary>
          <div className="mt-3 space-y-3 text-[0.95rem] leading-relaxed text-ink-600">
            {transcript.map((line, i) => (
              <p key={i}>{line}</p>
            ))}
          </div>
        </details>
      )}
    </div>
  );
}
