/**
 * Generates the WebVTT caption file from the cue data in src/data/brand-film.ts,
 * so the track and the on-page transcript cannot drift apart.
 *
 *   node scripts/build-vtt.mjs
 *
 * Re-run after editing `brandFilmCues`.
 */
import { readFileSync, writeFileSync } from "node:fs";

const SRC = "src/data/brand-film.ts";
const OUT = "public/video/seaside-brand-film.en.vtt";

// Parse the cue literals out of the TS source — avoids needing a TS runtime.
const src = readFileSync(SRC, "utf8");
const block = src.slice(
  src.indexOf("export const brandFilmCues"),
  src.indexOf("];", src.indexOf("export const brandFilmCues"))
);

const cues = [...block.matchAll(
  /\{\s*start:\s*([\d.]+),\s*end:\s*([\d.]+),\s*text:\s*"((?:[^"\\]|\\.)*)"\s*\}/g
)].map((m) => ({
  start: parseFloat(m[1]),
  end: parseFloat(m[2]),
  text: m[3].replace(/\\"/g, '"'),
}));

if (!cues.length) throw new Error("no cues parsed — check the shape of " + SRC);

const stamp = (s) => {
  const h = String(Math.floor(s / 3600)).padStart(2, "0");
  const m = String(Math.floor((s % 3600) / 60)).padStart(2, "0");
  const sec = (s % 60).toFixed(3).padStart(6, "0");
  return `${h}:${m}:${sec}`;
};

const body = cues
  .map((c, i) => `${i + 1}\n${stamp(c.start)} --> ${stamp(c.end)}\n${c.text}`)
  .join("\n\n");

const header = [
  "WEBVTT",
  "",
  "NOTE",
  "Generated by scripts/build-vtt.mjs from src/data/brand-film.ts — do not edit",
  "by hand. Transcribed from the film's on-screen text cards; the audio track has",
  "not been verified against it. See SW-007 in ISSUES.md.",
].join("\n");

writeFileSync(OUT, `${header}\n\n${body}\n`);
console.log(`wrote ${OUT} — ${cues.length} cues, ${cues[0].start}s to ${cues.at(-1).end}s`);
